interface _Rule
  def apply: (Integer) -> String
end

class FizzBuzzRule
  include _Rule
end

class FizzRule
  include _Rule
end

class BuzzRule
  include _Rule
end

class NumberRule
  include _Rule
end

class FizzBuzzProcessor
  def initialize: (Array[_Rule]) -> void
  def process: (Integer) -> String
end
